services:
  backend-korea-investment:
    container_name: korea-investment-api
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - NODE_ENV=local
        - APP_NAME=backend-korea-investment
    networks:
      - korea-investment-network
  redis:
    image: redis:8.4.0-alpine3.22
    container_name: korea-investment-redis
    ports:
      - '6379:6379'
    networks:
      - korea-investment-network

networks:
  korea-investment-network:
    driver: bridge
