services:
  backend-korea-investment:
    container_name: korea-investment-api
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - NODE_ENV=local
        - APP_NAME=backend-korea-investment
    networks:
      - korea-investment-network
  mysql:
    container_name: korea-investment-mysql
    image: mysql:8.4.7
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '!@#nest!@#'
      MYSQL_DATABASE: 'korea-investment'
      MYSQL_USER: 'nest'
      MYSQL_PASSWORD: 'nest!@#'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      LANG: ko_KR.UTF-8
      LANGUAGE: ko_KR:ko
      LC_ALL: ko_KR.UTF-8
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - korea-investment-network
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-p !@#nest!@#' ]
      retries: 3
      timeout: 10s
  redis:
    image: redis:8.4.0-alpine3.22
    container_name: korea-investment-redis
    ports:
      - '6379:6379'
    networks:
      - korea-investment-network

networks:
  korea-investment-network:
    driver: bridge
